#!/bin/zsh
# Builds Nightwatch.app and its desktop widget with Xcode, from project.yml (generated by xcodegen), signs it, installs it
# to /Applications and launches it. With --no-install it stops at build/Nightwatch.app, which release.sh and appstore.sh
# re-sign for the download and the Mac App Store.
set -euo pipefail
cd "$(dirname "$0")/.."
fail() { print -u2 "build-app: $1"; exit 1 }
xcrun --find xcodebuild >/dev/null 2>&1 || fail "Xcode is not installed"
command -v xcodegen >/dev/null || fail "xcodegen is not installed: brew install xcodegen"
PLIST=Sources/Nightwatch/Info.plist
BUNDLE_ID=$(/usr/libexec/PlistBuddy -c 'Print :CFBundleIdentifier' "$PLIST")
APP=build/Nightwatch.app
mkdir -p build; rm -rf "$APP"
xcodegen generate --quiet
# The generated project gets the root Package.resolved, so Xcode links exactly the dependency versions the tests use.
PINS=Nightwatch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm
mkdir -p "$PINS" && cp Package.resolved "$PINS/"
# NIGHTWATCH_APPSTORE=1 (set by scripts/appstore.sh): the Mac App Store variant, which has no widget helper and no update
# check (Sources/Nightwatch/Distribution.swift).
[[ "${NIGHTWATCH_APPSTORE:-}" == 1 ]] && CONDITIONS=APPSTORE || CONDITIONS=""
XCB=(xcodebuild -project Nightwatch.xcodeproj -scheme Nightwatch -configuration Release -derivedDataPath build/xcode
     -onlyUsePackageVersionsFromResolvedFile "SWIFT_ACTIVE_COMPILATION_CONDITIONS=$CONDITIONS"
     MARKETING_VERSION="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "$PLIST")"
     CURRENT_PROJECT_VERSION="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleVersion' "$PLIST")")
PRODUCT=build/xcode/Build/Products/Release/Nightwatch.app

# Signed build when an Apple Development identity and a provisioning profile for this bundle id exist: WeatherKit and the
# widget then work. Otherwise ad hoc, without the widget, and the app falls back to Open-Meteo.
IDENTITY=$(security find-identity -v -p codesigning 2>/dev/null | awk -F'"' '/Apple Development/{print $2; exit}')
PROFILE=""
for p in ~/Library/Developer/Xcode/UserData/Provisioning\ Profiles/*.provisionprofile(N) ~/Library/MobileDevice/Provisioning\ Profiles/*.provisionprofile(N); do
  # Development profiles only, which list devices. A Developer ID profile (ProvisionsAllDevices) belongs to scripts/release.sh
  # and a Mac App Store profile (neither key) to scripts/appstore.sh.
  PL=$(security cms -D -i "$p" 2>/dev/null) || continue
  if [[ "$PL" == *".$BUNDLE_ID</string>"* && "$PL" == *"<key>ProvisionedDevices</key>"* && "$PL" != *"<key>ProvisionsAllDevices</key>"* ]]; then PROFILE="$p"; break; fi
done
if [[ -n "$IDENTITY" && -n "$PROFILE" ]]; then
  TEAM=$(security cms -D -i "$PROFILE" | plutil -extract TeamIdentifier.0 raw -)
  # Automatic signing: Xcode signs the widget and the app with Sources/Nightwatch/Nightwatch.entitlements and the widget's
  # own, and fetches the development profiles itself. The app group is named with the team ID (no portal registration).
  "${XCB[@]}" DEVELOPMENT_TEAM="$TEAM" -allowProvisioningUpdates build > build/xcode.log 2>&1 || fail "the Xcode build failed: see build/xcode.log"
  ditto "$PRODUCT" "$APP"
  [[ -d "$APP/Contents/PlugIns/NightwatchWidget.appex" ]] || fail "the build has no widget: see build/xcode.log"
  echo "Signed as $IDENTITY, with WeatherKit and the widget"
else
  "${XCB[@]}" CODE_SIGNING_ALLOWED=NO build > build/xcode.log 2>&1 || fail "the Xcode build failed: see build/xcode.log"
  ditto "$PRODUCT" "$APP"
  rm -rf "$APP/Contents/PlugIns"   # the widget needs the App Group a signed build carries
  rm -rf "$APP/Contents/XPCServices"   # and with no widget there is no old widget process to end
  # Sandboxed like every other build (v0.7.0), so files live in the same place whichever way it was built.
  cat > build/Nightwatch.entitlements <<ENT
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>com.apple.security.personal-information.location</key><true/>
  <key>com.apple.security.app-sandbox</key><true/>
  <key>com.apple.security.network.client</key><true/>
  <key>com.apple.security.temporary-exception.files.home-relative-path.read-only</key><array><string>/Library/Application Support/Nightwatch/</string><string>/Library/Caches/Nightwatch/</string></array>
  <key>com.apple.security.files.user-selected.read-only</key><true/>
</dict></plist>
ENT
  # No App Group without a team, so no group name either: the app then skips the widget snapshot entirely.
  /usr/libexec/PlistBuddy -c "Delete :NightwatchAppGroup" "$APP/Contents/Info.plist"
  codesign --force --sign - --entitlements build/Nightwatch.entitlements "$APP"
  echo "Signed ad hoc (no Apple Development identity or profile for $BUNDLE_ID): Open-Meteo only, no widget"
fi
if [[ "${1:-}" == "--no-install" ]]; then echo "Built $APP"; exit 0; fi
pkill -x Nightwatch || true
# macOS keeps a widget's process alive across reinstalls and goes on drawing with the code it first loaded (on 25 Sep 2026
# the desktop showed a build three hours old). Ending it makes the system relaunch the widget from the new copy.
pkill -f "Nightwatch.app/Contents/PlugIns/NightwatchWidget.appex/" || true
rm -rf /Applications/Nightwatch.app
mv "$APP" /Applications/Nightwatch.app   # moved, not copied, so no second copy lingers in build/
# Xcode registers every product it builds with Launch Services under the same bundle id, and Spotlight registers any app
# it indexes. With several on record, the app launcher can settle on a copy under build/ and leave Nightwatch out of
# Applications (29 Sep 2026), so Spotlight skips build/ and only the installed copy stays registered.
touch build/.metadata_never_index
LSREG=/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister
"$LSREG" -u "$PWD/$APP" 2>/dev/null || true   # the path it was built at, now empty
find build -maxdepth 6 -type d -name "Nightwatch.app" -prune | while read -r copy; do "$LSREG" -u "$copy" 2>/dev/null || true; done
"$LSREG" -f -R -trusted /Applications/Nightwatch.app
open /Applications/Nightwatch.app
echo "Installed and launched /Applications/Nightwatch.app"
